 const changeHandlesatir1sutun1 = (e)=>{setsatir1sutun1(e.target.value)}
 const changeHandlesatir1sutun2 = (e)=>{setsatir1sutun2(e.target.value)}
 const changeHandlesatir1sutun3 = (e)=>{setsatir1sutun3(e.target.value)}
 const changeHandlesatir1sutun4 = (e)=>{setsatir1sutun4(e.target.value)}
 const changeHandlesatir1sutun5 = (e)=>{setsatir1sutun5(e.target.value)}
 const changeHandlesatir1sutun6 = (e)=>{setsatir1sutun6(e.target.value)}
 const changeHandlesatir1sutun7 = (e)=>{setsatir1sutun7(e.target.value)}
 const changeHandlesatir1sutun8 = (e)=>{setsatir1sutun8(e.target.value)}
 const changeHandlesatir1sutun9 = (e)=>{setsatir1sutun9(e.target.value)}
 const changeHandlesatir2sutun1 = (e)=>{setsatir2sutun1(e.target.value)}
 const changeHandlesatir2sutun2 = (e)=>{setsatir2sutun2(e.target.value)}
 const changeHandlesatir2sutun3 = (e)=>{setsatir2sutun3(e.target.value)}
 const changeHandlesatir2sutun4 = (e)=>{setsatir2sutun4(e.target.value)}
 const changeHandlesatir2sutun5 = (e)=>{setsatir2sutun5(e.target.value)}
 const changeHandlesatir2sutun6 = (e)=>{setsatir2sutun6(e.target.value)}
 const changeHandlesatir2sutun7 = (e)=>{setsatir2sutun7(e.target.value)}
 const changeHandlesatir2sutun8 = (e)=>{setsatir2sutun8(e.target.value)}
 const changeHandlesatir2sutun9 = (e)=>{setsatir2sutun9(e.target.value)}
 const changeHandlesatir3sutun1 = (e)=>{setsatir3sutun1(e.target.value)}
 const changeHandlesatir3sutun2 = (e)=>{setsatir3sutun2(e.target.value)}
 const changeHandlesatir3sutun3 = (e)=>{setsatir3sutun3(e.target.value)}
 const changeHandlesatir3sutun4 = (e)=>{setsatir3sutun4(e.target.value)}
 const changeHandlesatir3sutun5 = (e)=>{setsatir3sutun5(e.target.value)}
 const changeHandlesatir3sutun6 = (e)=>{setsatir3sutun6(e.target.value)}
 const changeHandlesatir3sutun7 = (e)=>{setsatir3sutun7(e.target.value)}
 const changeHandlesatir3sutun8 = (e)=>{setsatir3sutun8(e.target.value)}
 const changeHandlesatir3sutun9 = (e)=>{setsatir3sutun9(e.target.value)}
 const changeHandlesatir4sutun1 = (e)=>{setsatir4sutun1(e.target.value)}
 const changeHandlesatir4sutun2 = (e)=>{setsatir4sutun2(e.target.value)}
 const changeHandlesatir4sutun3 = (e)=>{setsatir4sutun3(e.target.value)}
 const changeHandlesatir4sutun4 = (e)=>{setsatir4sutun4(e.target.value)}
 const changeHandlesatir4sutun5 = (e)=>{setsatir4sutun5(e.target.value)}
 const changeHandlesatir4sutun6 = (e)=>{setsatir4sutun6(e.target.value)}
 const changeHandlesatir4sutun7 = (e)=>{setsatir4sutun7(e.target.value)}
 const changeHandlesatir4sutun8 = (e)=>{setsatir4sutun8(e.target.value)}
 const changeHandlesatir4sutun9 = (e)=>{setsatir4sutun9(e.target.value)}
 const changeHandlesatir5sutun1 = (e)=>{setsatir5sutun1(e.target.value)}
 const changeHandlesatir5sutun2 = (e)=>{setsatir5sutun2(e.target.value)}
 const changeHandlesatir5sutun3 = (e)=>{setsatir5sutun3(e.target.value)}
 const changeHandlesatir5sutun4 = (e)=>{setsatir5sutun4(e.target.value)}
 const changeHandlesatir5sutun5 = (e)=>{setsatir5sutun5(e.target.value)}
 const changeHandlesatir5sutun6 = (e)=>{setsatir5sutun6(e.target.value)}
 const changeHandlesatir5sutun7 = (e)=>{setsatir5sutun7(e.target.value)}
 const changeHandlesatir5sutun8 = (e)=>{setsatir5sutun8(e.target.value)}
 const changeHandlesatir5sutun9 = (e)=>{setsatir5sutun9(e.target.value)}
 const changeHandlesatir6sutun1 = (e)=>{setsatir6sutun1(e.target.value)}
 const changeHandlesatir6sutun2 = (e)=>{setsatir6sutun2(e.target.value)}
 const changeHandlesatir6sutun3 = (e)=>{setsatir6sutun3(e.target.value)}
 const changeHandlesatir6sutun4 = (e)=>{setsatir6sutun4(e.target.value)}
 const changeHandlesatir6sutun5 = (e)=>{setsatir6sutun5(e.target.value)}
 const changeHandlesatir6sutun6 = (e)=>{setsatir6sutun6(e.target.value)}
 const changeHandlesatir6sutun7 = (e)=>{setsatir6sutun7(e.target.value)}
 const changeHandlesatir6sutun8 = (e)=>{setsatir6sutun8(e.target.value)}
 const changeHandlesatir6sutun9 = (e)=>{setsatir6sutun9(e.target.value)}
 const changeHandlesatir7sutun1 = (e)=>{setsatir7sutun1(e.target.value)}
 const changeHandlesatir7sutun2 = (e)=>{setsatir7sutun2(e.target.value)}
 const changeHandlesatir7sutun3 = (e)=>{setsatir7sutun3(e.target.value)}
 const changeHandlesatir7sutun4 = (e)=>{setsatir7sutun4(e.target.value)}
 const changeHandlesatir7sutun5 = (e)=>{setsatir7sutun5(e.target.value)}
 const changeHandlesatir7sutun6 = (e)=>{setsatir7sutun6(e.target.value)}
 const changeHandlesatir7sutun7 = (e)=>{setsatir7sutun7(e.target.value)}
 const changeHandlesatir7sutun8 = (e)=>{setsatir7sutun8(e.target.value)}
 const changeHandlesatir7sutun9 = (e)=>{setsatir7sutun9(e.target.value)}
 const changeHandlesatir8sutun1 = (e)=>{setsatir8sutun1(e.target.value)}
 const changeHandlesatir8sutun2 = (e)=>{setsatir8sutun2(e.target.value)}
 const changeHandlesatir8sutun3 = (e)=>{setsatir8sutun3(e.target.value)}
 const changeHandlesatir8sutun4 = (e)=>{setsatir8sutun4(e.target.value)}
 const changeHandlesatir8sutun5 = (e)=>{setsatir8sutun5(e.target.value)}
 const changeHandlesatir8sutun6 = (e)=>{setsatir8sutun6(e.target.value)}
 const changeHandlesatir8sutun7 = (e)=>{setsatir8sutun7(e.target.value)}
 const changeHandlesatir8sutun8 = (e)=>{setsatir8sutun8(e.target.value)}
 const changeHandlesatir8sutun9 = (e)=>{setsatir8sutun9(e.target.value)}
 const changeHandlesatir9sutun1 = (e)=>{setsatir9sutun1(e.target.value)}
 const changeHandlesatir9sutun2 = (e)=>{setsatir9sutun2(e.target.value)}
 const changeHandlesatir9sutun3 = (e)=>{setsatir9sutun3(e.target.value)}
 const changeHandlesatir9sutun4 = (e)=>{setsatir9sutun4(e.target.value)}
 const changeHandlesatir9sutun5 = (e)=>{setsatir9sutun5(e.target.value)}
 const changeHandlesatir9sutun6 = (e)=>{setsatir9sutun6(e.target.value)}
 const changeHandlesatir9sutun7 = (e)=>{setsatir9sutun7(e.target.value)}
 const changeHandlesatir9sutun8 = (e)=>{setsatir9sutun8(e.target.value)}
 const changeHandlesatir9sutun9 = (e)=>{setsatir9sutun9(e.target.value)}